package bundler

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/functionfly/fly/internal/manifest"
)

// InstallDependencies installs the dependencies specified in the manifest.
// It handles different package managers based on the runtime.
func InstallDependencies(manifest *manifest.Manifest) error {
	if manifest == nil {
		return NewBundlerError("dependency install", "manifest cannot be nil")
	}

	if manifest.Dependencies == nil || len(manifest.Dependencies) == 0 {
		// No dependencies to install
		return nil
	}

	switch {
	case strings.HasPrefix(manifest.Runtime, "node"):
		return installNPMDependencies(manifest.Dependencies)
	case strings.HasPrefix(manifest.Runtime, "python"):
		return installPipDependencies(manifest.Dependencies)
	case manifest.Runtime == "deno":
		// Deno handles dependencies differently - they can be imported directly
		return nil
	case manifest.Runtime == "bun":
		return installBunDependencies(manifest.Dependencies)
	default:
		return &RuntimeNotSupportedError{
			Runtime:   manifest.Runtime,
			Supported: []string{"node18", "node20", "python3.11", "deno", "bun"},
		}
	}
}

// installNPMDependencies installs Node.js dependencies using npm
func installNPMDependencies(deps map[string]string) error {
	// Check if package.json exists, create if not
	if _, err := os.Stat("package.json"); os.IsNotExist(err) {
		if err := createPackageJSON(deps); err != nil {
			return NewBundlerErrorWithCause("npm install", "failed to create package.json", err)
		}
	}

	// Check if node_modules exists and is up to date
	if needsNPMInstall(deps) {
		fmt.Println("Installing npm dependencies...")
		if err := runCommand("npm", "install"); err != nil {
			return NewDependencyErrorWithCause("npm install", "all", "npm install failed", err)
		}
		fmt.Println("✓ npm dependencies installed")
	} else {
		fmt.Println("✓ npm dependencies already up to date")
	}

	return nil
}

// installPipDependencies installs Python dependencies using pip
func installPipDependencies(deps map[string]string) error {
	// Check if requirements.txt exists, create if not
	if _, err := os.Stat("requirements.txt"); os.IsNotExist(err) {
		if err := createRequirementsTxt(deps); err != nil {
			return NewBundlerErrorWithCause("pip install", "failed to create requirements.txt", err)
		}
	}

	// Check if dependencies are installed
	if needsPipInstall(deps) {
		fmt.Println("Installing pip dependencies...")
		if err := runCommand("pip", "install", "-r", "requirements.txt"); err != nil {
			return NewDependencyErrorWithCause("pip install", "all", "pip install failed", err)
		}
		fmt.Println("✓ pip dependencies installed")
	} else {
		fmt.Println("✓ pip dependencies already up to date")
	}

	return nil
}

// needsNPMInstall checks if npm install is needed by comparing package.json with node_modules
func needsNPMInstall(deps map[string]string) bool {
	// For simplicity, we'll always install if node_modules doesn't exist
	// In a production system, you'd want more sophisticated dependency checking
	if _, err := os.Stat("node_modules"); os.IsNotExist(err) {
		return true
	}

	// Check if package-lock.json exists and is newer than package.json
	packageStat, err := os.Stat("package.json")
	if err != nil {
		return true
	}

	lockStat, err := os.Stat("package-lock.json")
	if err != nil {
		// No lock file, need to install
		return true
	}

	// If package.json is newer than package-lock.json, reinstall
	return packageStat.ModTime().After(lockStat.ModTime())
}

// needsPipInstall checks if pip install is needed
func needsPipInstall(deps map[string]string) bool {
	// For simplicity, check if any of the packages are not installed
	// In a production system, you'd want to check requirements.txt vs installed packages
	for pkg := range deps {
		if !isPythonPackageInstalled(pkg) {
			return true
		}
	}
	return false
}

// isPythonPackageInstalled checks if a Python package is installed
func isPythonPackageInstalled(pkgName string) bool {
	// Use pip show to check if package is installed
	cmd := exec.Command("pip", "show", pkgName)
	cmd.Stdout = nil
	cmd.Stderr = nil
	err := cmd.Run()
	return err == nil
}

// createPackageJSON creates a package.json file from manifest dependencies
func createPackageJSON(deps map[string]string) error {
	content := `{
  "name": "functionfly-function",
  "version": "1.0.0",
  "description": "Generated by FunctionFly bundler",
  "dependencies": {
`

	depsList := make([]string, 0, len(deps))
	for name, version := range deps {
		depsList = append(depsList, fmt.Sprintf(`    "%s": "%s"`, name, version))
	}

	content += strings.Join(depsList, ",\n")
	content += `
  }
}
`

	return os.WriteFile("package.json", []byte(content), 0644)
}

// createRequirementsTxt creates a requirements.txt file from manifest dependencies
func createRequirementsTxt(deps map[string]string) error {
	var lines []string
	for name, version := range deps {
		if version == "" || version == "*" {
			lines = append(lines, name)
		} else {
			lines = append(lines, fmt.Sprintf("%s%s", name, version))
		}
	}

	content := strings.Join(lines, "\n") + "\n"
	return os.WriteFile("requirements.txt", []byte(content), 0644)
}

// runCommand executes a command and returns an error if it fails
func runCommand(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("command failed: %s %s\nOutput: %s\nError: %v",
			name, strings.Join(args, " "), string(output), err)
	}
	return nil
}

// InstallDependenciesWithWorkingDirectory installs dependencies with explicit working directory support
func InstallDependenciesWithWorkingDirectory(manifest *manifest.Manifest, workingDir string) error {
	if manifest == nil {
		return NewBundlerError("dependency install", "manifest cannot be nil")
	}

	// Resolve and validate working directory
	resolvedDir, err := ResolveWorkingDirectory(workingDir)
	if err != nil {
		return NewBundlerErrorWithCause("dependency install", "failed to resolve working directory", err)
	}

	// Execute dependency installation within the specified working directory
	return WithWorkingDirectory(resolvedDir, func() error {
		return InstallDependencies(manifest)
	})
}

// PackageJSON represents a parsed package.json file
type PackageJSON struct {
	Name                 string            `json:"name"`
	Version              string            `json:"version"`
	Description          string            `json:"description"`
	Main                 string            `json:"main"`
	Dependencies         map[string]string `json:"dependencies"`
	DevDependencies      map[string]string `json:"devDependencies"`
	PeerDependencies     map[string]string `json:"peerDependencies"`
	OptionalDependencies map[string]string `json:"optionalDependencies"`
	BundledDependencies  []string          `json:"bundledDependencies"`
	BundleDependencies   []string          `json:"bundleDependencies"` // alias for bundledDependencies
}

// ParsePackageJSON parses a package.json file from the given path
func ParsePackageJSON(path string) (*PackageJSON, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, NewBundlerErrorWithCause("parse package.json", "failed to read file", err)
	}

	var pkg PackageJSON
	if err := json.Unmarshal(data, &pkg); err != nil {
		return nil, NewBundlerErrorWithCause("parse package.json", "failed to parse JSON", err)
	}

	// Handle bundleDependencies as alias for bundledDependencies
	if len(pkg.BundledDependencies) == 0 && len(pkg.BundleDependencies) > 0 {
		pkg.BundledDependencies = pkg.BundleDependencies
	}

	return &pkg, nil
}

// ParsePackageJSONFromDir parses a package.json file from a directory
func ParsePackageJSONFromDir(dir string) (*PackageJSON, error) {
	path := filepath.Join(dir, "package.json")
	return ParsePackageJSON(path)
}

// HasDependencies checks if the package.json has any dependencies
func (p *PackageJSON) HasDependencies() bool {
	return p.Dependencies != nil && len(p.Dependencies) > 0
}

// GetAllDependencies returns all dependencies (including optional)
func (p *PackageJSON) GetAllDependencies() map[string]string {
	result := make(map[string]string)

	if p.Dependencies != nil {
		for k, v := range p.Dependencies {
			result[k] = v
		}
	}

	if p.OptionalDependencies != nil {
		for k, v := range p.OptionalDependencies {
			result[k] = v
		}
	}

	return result
}

// PackageValidationError represents a validation error for package.json
type PackageValidationError struct {
	Field   string
	Message string
}

func (e PackageValidationError) Error() string {
	return fmt.Sprintf("%s: %s", e.Field, e.Message)
}

// ValidatePackageJSON validates the package.json for common issues
func ValidatePackageJSON(pkg *PackageJSON) []PackageValidationError {
	var errors []PackageValidationError

	if pkg.Name == "" {
		errors = append(errors, PackageValidationError{
			Field:   "name",
			Message: "package name is required",
		})
	}

	// Validate package name follows npm naming rules
	if pkg.Name != "" && !isValidPackageName(pkg.Name) {
		errors = append(errors, PackageValidationError{
			Field:   "name",
			Message: "invalid package name - must match pattern ^[a-zA-Z0-9-_.]+$",
		})
	}

	// Check for version if dependencies exist
	if pkg.Version == "" && pkg.HasDependencies() {
		errors = append(errors, PackageValidationError{
			Field:   "version",
			Message: "package version is recommended when using dependencies",
		})
	}

	return errors
}

// FindPackageJSON searches for package.json starting from the given directory
func FindPackageJSON(startDir string) (string, error) {
	dir := startDir
	for {
		pkgPath := filepath.Join(dir, "package.json")
		if _, err := os.Stat(pkgPath); err == nil {
			return pkgPath, nil
		}

		// Go up one directory
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return "", fmt.Errorf("package.json not found in %s or any parent directory", startDir)
}

// isValidPackageName checks if a package name is valid according to npm rules
func isValidPackageName(name string) bool {
	// Package names must be lowercase, can contain hyphens, underscores, dots
	// Cannot start with . or _
	// Cannot contain URL unsafe characters
	if len(name) == 0 || len(name) > 214 {
		return false
	}

	for _, c := range name {
		if !((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.' || c == '@') {
			return false
		}
	}

	return true
}

// installBunDependencies installs Bun dependencies using bun install
func installBunDependencies(deps map[string]string) error {
	// Check if package.json exists, create if not
	if _, err := os.Stat("package.json"); os.IsNotExist(err) {
		if err := createPackageJSON(deps); err != nil {
			return NewBundlerErrorWithCause("bun install", "failed to create package.json", err)
		}
	}

	// Check if bun.lockb exists and is up to date
	if needsBunInstall(deps) {
		fmt.Println("Installing bun dependencies...")
		if err := runCommand("bun", "install"); err != nil {
			return NewDependencyErrorWithCause("bun install", "all", "bun install failed", err)
		}
		fmt.Println("✓ bun dependencies installed")
	} else {
		fmt.Println("✓ bun dependencies already up to date")
	}

	return nil
}

// needsBunInstall checks if bun install is needed
func needsBunInstall(deps map[string]string) bool {
	// Always install if node_modules doesn't exist
	if _, err := os.Stat("node_modules"); os.IsNotExist(err) {
		return true
	}

	// Check if bun.lockb exists and is newer than package.json
	packageStat, err := os.Stat("package.json")
	if err != nil {
		return true
	}

	lockStat, err := os.Stat("bun.lockb")
	if err != nil {
		// No lock file, need to install
		return true
	}

	// If package.json is newer than bun.lockb, reinstall
	return packageStat.ModTime().After(lockStat.ModTime())
}
